# Walks the AST and emits C source code.
# All type mappings, built-in implementations, operator strings,
# and header lists come from LangSpec — nothing is hard-coded.

from __future__ import annotations
from .spec import LangSpec, BuiltinSpec
from . import ast as A


class CodegenError(Exception):
    pass


class CCodegen:
    def __init__(self, spec: LangSpec):
        self.spec = spec
        self._indent_unit = spec.codegen.indent
        self._depth = 0
        self._lines: list[str] = []

    # ── Public API ────────────────────────────────────────────

    def generate(self, program: A.Program) -> str:
        self._lines = []
        self._emit_header()
        self._emit_runtime()

        # Forward-declare all user functions
        for fn in program.functions:
            self._emit_forward_decl(fn)
        self._line("")

        for fn in program.functions:
            self._emit_func(fn)

        return "\n".join(self._lines) + "\n"

    # ── Helpers ───────────────────────────────────────────────

    def _indent(self) -> str:
        return self._indent_unit * self._depth

    def _line(self, s: str = ""):
        self._lines.append(self._indent() + s)

    def _c_type(self, type_name: str) -> str:
        tm = self.spec.type_map
        if type_name not in tm:
            raise CodegenError(f"[idot codegen] Unknown type: {type_name!r}")
        return tm[type_name].c_type

    # ── File header / runtime ─────────────────────────────────

    def _emit_header(self):
        cg = self.spec.codegen
        guard = cg.runtime_guard
        self._line(f"/* Generated by idot {self.spec.version} — do not edit */")
        self._line(f"#ifndef {guard}")
        self._line(f"#define {guard}")
        self._line()
        for inc in cg.include_headers:
            self._line(f"#include {inc}")
        self._line()

    def _emit_runtime(self):
        """Emit inline implementations of built-in functions."""
        if not self.spec.builtins:
            return
        self._line("/* ── idot built-ins ───────────────────────────────── */")
        for b in self.spec.builtins:
            params_c = ", ".join(
                f"{self._c_type(p)} _idot_p{i}"
                for i, p in enumerate(b.params)
            )
            ret_c = self._c_type(b.ret)
            impl = b.c_impl
            for i in range(len(b.params)):
                impl = impl.replace(f"${i}", f"_idot_p{i}")
            self._line(f"static inline {ret_c} {b.name}({params_c}) {{")
            self._depth += 1
            if b.ret == "void":
                self._line(f"{impl};")
            else:
                self._line(f"return {impl};")
            self._depth -= 1
            self._line("}")
            self._line()

    # ── Function ──────────────────────────────────────────────

    def _emit_forward_decl(self, fn: A.FuncDef):
        if fn.name == self.spec.codegen.entry_point:
            self._line("int main(void);")
        else:
            sig = self._func_signature(fn)
            self._line(f"{sig};")

    def _emit_func(self, fn: A.FuncDef):
        is_entry = fn.name == self.spec.codegen.entry_point
        if is_entry:
            # idot's entry fn becomes C's main
            self._line(f"int main(void) {{")
        else:
            sig = self._func_signature(fn)
            self._line(f"{sig} {{")
        self._depth += 1
        for stmt in fn.body:
            self._emit_stmt(stmt)
        if is_entry:
            self._line("return 0;")
        self._depth -= 1
        self._line("}")
        self._line()

    def _func_signature(self, fn: A.FuncDef) -> str:
        ret = self._c_type(fn.return_type)
        params = ", ".join(
            f"{self._c_type(p.type_name)} {p.name}" for p in fn.params
        )
        if not params:
            params = "void"
        return f"{ret} {fn.name}({params})"

    # ── Statements ────────────────────────────────────────────

    def _emit_stmt(self, node: A.Node):
        if isinstance(node, A.VarDecl):
            self._emit_var_decl(node)
        elif isinstance(node, A.Return):
            self._emit_return(node)
        elif isinstance(node, A.If):
            self._emit_if(node)
        elif isinstance(node, A.While):
            self._emit_while(node)
        elif isinstance(node, A.For):
            self._emit_for(node)
        elif isinstance(node, A.Assign):
            self._line(f"{node.target} = {self._expr(node.value)};")
        elif isinstance(node, A.Call):
            self._line(f"{self._expr(node)};")
        else:
            # Generic expression statement
            self._line(f"{self._expr(node)};")

    def _emit_var_decl(self, node: A.VarDecl):
        c_type = self._c_type(node.type_name)
        # const for immutable
        qualifier = "" if node.mutable else "const "
        if node.value is not None:
            self._line(f"{qualifier}{c_type} {node.name} = {self._expr(node.value)};")
        else:
            self._line(f"{qualifier}{c_type} {node.name};")

    def _emit_return(self, node: A.Return):
        if node.value:
            self._line(f"return {self._expr(node.value)};")
        else:
            self._line("return;")

    def _emit_if(self, node: A.If):
        self._line(f"if ({self._expr(node.condition)}) {{")
        self._depth += 1
        for s in node.then_block:
            self._emit_stmt(s)
        self._depth -= 1
        if node.else_block:
            self._line("} else {")
            self._depth += 1
            for s in node.else_block:
                self._emit_stmt(s)
            self._depth -= 1
        self._line("}")

    def _emit_while(self, node: A.While):
        self._line(f"while ({self._expr(node.condition)}) {{")
        self._depth += 1
        for s in node.body:
            self._emit_stmt(s)
        self._depth -= 1
        self._line("}")

    def _emit_for(self, node: A.For):
        # idot: for x in expr  → C: for(int x = 0; x < expr; x++)
        # (range-style — expand as you add iterator types)
        iterable = self._expr(node.iterable)
        self._line(f"for (int64_t {node.var} = 0; {node.var} < {iterable}; {node.var}++) {{")
        self._depth += 1
        for s in node.body:
            self._emit_stmt(s)
        self._depth -= 1
        self._line("}")

    # ── Expressions ───────────────────────────────────────────

    def _expr(self, node: A.Node) -> str:
        if isinstance(node, A.IntLiteral):
            return str(node.value)
        if isinstance(node, A.FloatLiteral):
            return str(node.value)
        if isinstance(node, A.BoolLiteral):
            return "true" if node.value else "false"
        if isinstance(node, A.StrLiteral):
            escaped = node.value.replace("\\", "\\\\").replace('"', '\\"') \
                                .replace("\n", "\\n").replace("\t", "\\t")
            return f'"{escaped}"'
        if isinstance(node, A.Identifier):
            return node.name
        if isinstance(node, A.Assign):
            return f"{node.target} = {self._expr(node.value)}"
        if isinstance(node, A.BinaryOp):
            return self._binary_op(node)
        if isinstance(node, A.UnaryOp):
            return self._unary_op(node)
        if isinstance(node, A.Call):
            return self._call(node)
        raise CodegenError(f"[idot codegen] Unknown AST node: {type(node).__name__}")

    def _binary_op(self, node: A.BinaryOp) -> str:
        # Map idot operator to C operator via spec
        c_op = node.op  # default: same symbol

        # Check spec binary ops
        for op_spec in self.spec.operators:
            if op_spec.symbol == node.op and op_spec.arity == "binary":
                c_op = op_spec.c_op
                break

        # Keyword operators
        if node.op == "and":
            c_op = "&&"
        elif node.op == "or":
            c_op = "||"

        left  = self._expr(node.left)
        right = self._expr(node.right)
        return f"({left} {c_op} {right})"

    def _unary_op(self, node: A.UnaryOp) -> str:
        if node.op == "not":
            return f"(!{self._expr(node.operand)})"
        for op_spec in self.spec.operators:
            if op_spec.symbol == node.op and op_spec.arity == "unary":
                return f"({op_spec.c_op}{self._expr(node.operand)})"
        return f"({node.op}{self._expr(node.operand)})"

    def _call(self, node: A.Call) -> str:
        args = ", ".join(self._expr(a) for a in node.args)
        return f"{node.callee}({args})"

    # ── Closing guard ─────────────────────────────────────────

    def generate(self, program: A.Program) -> str:  # noqa: F811
        self._lines = []
        self._emit_header()
        self._emit_runtime()

        for fn in program.functions:
            self._emit_forward_decl(fn)
        self._line("")

        for fn in program.functions:
            self._emit_func(fn)

        self._line(f"#endif /* {self.spec.codegen.runtime_guard} */")
        return "\n".join(self._lines) + "\n"